# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'rails_launcher'
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

def sample_path(name)
  File.expand_path("../sample_worlds/#{name}.rb", __FILE__)
end

def sample_world(name)
  RailsLauncher::DSL.new_world File.read(sample_path(name))
end

def content_of_file(path_regexp)
  matches = constructor.file_entities.select { |f| f.path.match path_regexp }
  case matches.size
  when 0
    fail("#{path_regexp} is expected to match a file constructed, but nothing matched")
  when 1
    return matches.first.file_content
  else
    fail("#{path_regexp} matches more than a file. " + matches.map(&:path).join(', '))
  end
end
